[project]
name = "gemini-pd2"
version = "0.1.0"
description = "Demo for Gemini API with tools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.16.1",
    "google-generativeai>=0.3.0",
    "python-dotenv>=1.0.0",
]

